#Einbinden der Pakete
```{r}
library(readr)
library(Metrics)
library(ggplot2)
library(dplyr)
library(e1071)

```
# Laden der Daten 
```{r}
umsatzdaten <- read_csv("https://raw.githubusercontent.com/christophson3/Data-science-Team-8/main/umsatzdaten.csv", 
    col_types = cols(X1 = col_skip()))

full_dataset <- read_csv("https://raw.githubusercontent.com/christophson3/Data-science-Team-8/main/full_dataset.csv", 
    col_types = cols(X1 = col_skip()))
```
# Daten Aufbereitung

```{r}
#Faktorisieren einzelner Variabeln sowohl im full_dataset als auch in umsatzdaten
umsatzdaten$Warengruppe <- factor(umsatzdaten$Warengruppe)
full_dataset$Warengruppe <- factor(full_dataset$Warengruppe)
umsatzdaten$Wertung <- factor(umsatzdaten$Wertung)
full_dataset$Wertung <- factor(full_dataset$Wertung)
umsatzdaten$KielerWoche <- factor(umsatzdaten$KielerWoche)
full_dataset$KielerWoche <- factor(full_dataset$KielerWoche)

```

# Aufteilung des Datensatzes in Trainings- und Testdaten
```{r}
# Zufallszähler setzen (um die zufällige Partitionierung bei jedem Durchlauf gleich zu halten)
set.seed(1)

# Zufällige Ziehung von Indizes für die Zeilen des Datensatzes, die dem Traininsdatensatz zugeordnet werden
indices_train <- sample(seq_len(nrow(umsatzdaten)), size = floor(0.80 * nrow(umsatzdaten)))

# Definition des Trainings- und Testdatensatz durch Selektion bzw. Deselektion der entsprechenden Datenzeilen
train_dataset <- train_dataset_org <- umsatzdaten[indices_train, ]
test_dataset <- umsatzdaten[-indices_train, ]
# zum beheben eines Fehlers der aufgetreten ist 
test_dataset = rbind(train_dataset[1,],test_dataset)
test_dataset = test_dataset[-1,]

```

# Training the SVM


```{r}
# alle nutzbaren Faktoren ergaben bei uns das beste Ergebnis
# mit dem Wochentag drin hatten wir noch ein besseres Ergebnis, aber dann funktionierte die Schätzung für den 5.Juni nicht mehr
svm_tune <- tune(svm, Umsatz ~ Vortagsumsatz + Temperatur + as.factor(Warengruppe) + as.factor(Wertung) + Umsatz_Vorwoche + Wettercode + Bewoelkung + Windgeschwindigkeit + as.factor(KielerWoche), data=train_dataset, ranges = list(epsilon = seq(0.2,1,0.1), cost = 2^(1:3)))
```
## Checking the Prediction Quality


SVM with cross validation and grid Search
```{r}
# Calculating the prediction for the training data using the best model according to the grid search

pred_train <- predict(svm_tune$best.model, train_dataset)
# Calculating the prediction quality for the training data using the MAPE
mape(train_dataset$Umsatz, pred_train)
```

### Test Data

SVM with cross validation and grid Search
```{r}
# Calculating the prediction for the test data using the best model according to the grid search
pred_test <- predict(svm_tune$best.model, test_dataset)
# Calculating the prediction quality for the test data using the MAPE
mape(test_dataset$Umsatz, pred_test)
```

### Vorhersage für den 05 Juni 2019

```{r}
# zusammenstellen des Datensatzes
newdata <- (filter(full_dataset, Datum == "2019-06-05"))

# irgendwie ist der Wochentag verloren gegangen, deswegen fügen wir den händisch nochmal ein
newdata['Wochentag'] <- "Mittwoch"

# vervielfachen der Zeile für jede Warengruppe eine
newdata <-rbind(newdata, newdata[rep(1, 6), ])

data <- filter(umsatzdaten, Datum == "2019-06-04")
data2 <-filter(umsatzdaten,Datum == "2019-05-28")

#Schleife um die Daten zusammen zu stellen
for (i in (1:6)) {
  
  newdata$Warengruppe[[i]] <- i
  newdata$Vortagsumsatz[[i]] <- data$Umsatz[i]
  newdata$Umsatz_Vorwoche[[i]] <- data2$Umsatz[i]
}
# in unserem Modell ergibt eine Schätzung für die Warengruppe 6 für den 5.Juni keinen Sinn

# es gab einen fehler obwohl es keine NA im Datensatz gab und wir alle Variablen reingepackt haben, also haben wir uns hier entschieden nochmal die Variabeln explizit aufzuführen
ModelVars = which(names(newdata) %in% 
    c("Vortagsumsatz" ,"Temperatur" , "Warengruppe" , "Wertung" , "Wettercode" , "Bewoelkung" , "Windgeschwindigkeit" , "KielerWoche", "Umsatz_Vorwoche", "Wochentag"))

# das hat einen Fehler behoben
newdata <- rbind(newdata[1,],data)
newdata <- newdata[-1,]

test2  = newdata[, ModelVars]

#das ist die Vorhersage
pred <- predict(svm_tune$best.model, test2)

show(pred)
```

### MAPE je Warengruppe
```{r}
# die Schleife geht durch alle Warengruppen durch
for (i in (1:6)){
  pred_test <- predict(svm_tune$best.model, filter(test_dataset, Warengruppe == i))
  lala <- filter(test_dataset,Warengruppe == i)
  listofmape[i] <- mape (lala$Umsatz, pred_test)
  cat(paste0("\n MAPE der Warengruppe ", i))
  cat(paste0(": \n ",format(mape (lala$Umsatz, pred_test)*100, digits=3, nsmall=2)))
}

```

